---

networks:
  gitea:
    external: true

services:
  server:
    image: gitea/gitea:1.22.3
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=${giteaDBPort}
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=${giteaDBUserName}
      - GITEA__database__PASSWD=${giteaDBUserPass}
    restart: always
    volumes:
      - /opt/gitea/data:/var/lib/gitea:Z
      - /opt/gitea/config:/etc/gitea:Z
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:2222"
    depends_on:
      - db
    networks:
      - gitea

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=${giteaDBUserName}
      - POSTGRES_PASSWORD=${giteaDBUserPass}
      - POSTGRES_DB=gitea
    volumes:
      - /opt/gitea/postgres:/var/lib/postgresql/data:Z
    networks:
      - gitea