---
version: "2.1"
services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
    volumes:
      - /opt/podmnts/freshrss/config:/config:Z
    ports:
      - 8070:80
    restart: unless-stopped